[project]
name = 'Quantum-Thought-Interface'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.neural-quantum-entanglement]
path = 'contracts/neural-quantum-entanglement.clar'
clarity_version = 2
epoch = 2.5

[contracts.thought-to-transaction]
path = 'contracts/thought-to-transaction.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
